### ISSUE TITLE
什么时候支持xuexiaoyi-to-xuexitong-tampermonkey-proxy项目

### ISSUE THREAD

**Issue by d4renk** [chettoy/FxxkStar#16]
https://github.com/SocialSisterYi/xuexiaoyi-to-xuexitong-tampermonkey-proxy

**Comment by chettoy** [comment]
添加题库的API很容易。但是，目前没有添加，因为它需要用户在使用xuexiaoyi题库之前抓取数据包，所以使用起来不方便。如果有足够多的人需要，我们可以优化我们的题库，可以统计大多数人选择的答案，并公开使用它

**Comment by d4renk** [comment]
> 添加题库的API很容易。但是，目前没有添加，因为它需要用户在使用xuexiaoyi题库之前抓取数据包，所以使用起来不方便。如果有足够多的人需要，我们可以优化我们的题库，可以统计大多数人选择的答案，并公开使用它

我添加这个项目api失败了 能以这个项目为例 举个例子吗？
