### ISSUE TITLE
为什么做题时这样抱错

### ISSUE THREAD

**Issue by 2682856025** [chettoy/FxxkStar#6]
<img width="984" alt="截屏2022-10-13 下午9 02 13" src="https://user-images.githubusercontent.com/106012957/195603580-04a38717-d6f4-44d7-beda-ae2bf055ee93.png">

Macos系统 pycharm软件 python版本3.10

**Comment by chettoy** [comment]
Thank you for the report! Fixed. [ab9bced](https://github.com/chettoy/FxxkStar/commit/ab9bced3ba4072bcd9761842cda1fa9f2f1547af)
