### ISSUE TITLE
视频也无法观看

### ISSUE THREAD

**Issue by 2682856025** [chettoy/FxxkStar#8]
<img width="518" alt="截屏2022-10-14 上午10 31 25" src="https://user-images.githubusercontent.com/106012957/195749187-00e9749d-0414-4d5e-b824-f140bcbf2a3e.png">
不知道什么原因

**Comment by chettoy** [comment]
After the chapter mode you will enter the video mode. 
You can exit chapter mode by typing q when selecting chapters again, or by typing autotest to automatically select each chapter, after which you will be prompted to sync the video's playback progress. 
在章节模式之后，你将进入视频模式
你可以在再次选择章节时输入q来退出章节模式，或者输入autotest来自动选择每个章节，之后会提示你同步视频的播放进度。
